apiVersion: v1
kind: Service
metadata:
  name: inventory-api-service
spec:
  type: NodePort
  selector:
    app: inventory-api # Arahkan traffic ke pod dengan label ini
  ports:
    - protocol: TCP
      port: 80      # Port di Service (Virtual)
      targetPort: 8080 # Port di Container Aplikasi
      nodePort: 30000 # Port yang kita tembak dari Laptop (30000-32767)