apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-api # Target deployment
  minReplicas: 1        # Minimal 1 pod nyala (saat sepi)
  maxReplicas: 10       # Maksimal 10 pod (saat badai traffic)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10 # Trigger di 50% CPU Usage