apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker
spec:
  replicas: 1 # Nanti kita coba scale up
  selector:
    matchLabels:
      app: inventory-worker
  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      containers:
        - name: inventory-worker
          image: inventory-worker:v1
          imagePullPolicy: Never
          
          # Inject Env Vars (Sama dengan API)
          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secret
          
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"