apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.env.appEnv | quote }}
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
  KAFKA_BROKERS: {{ .Values.env.kafkaBrokers | quote }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.otelExporterEndpoint | quote }}