name: Go Backend CI/CD

# Trigger: Jalan setiap Push atau PR ke main
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # === JOB 1: TESTING (CI) ===
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    # Service Database & Redis untuk keperluan Testing
    services:
      postgres:
        image: postgres:alpine
        env:
          # Menggunakan hardcode untuk testing environment (aman & simpel)
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: inventory_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24" # Disamakan dengan Dockerfile

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        env:
          # Env vars ini harus cocok dengan 'services' di atas
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: user_test
          DB_PASSWORD: password_test
          DB_NAME: inventory_db_test
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: rahasia_testing_aja
        run: go test ./... -v -cover

  # === JOB 2: DELIVERY (CD) ===
  build-and-push:
    name: Build & Push Docker Image
    needs: test # Job ini cuma jalan kalau job 'test' SUKSES
    runs-on: ubuntu-latest
    # Hanya jalan kalau event-nya PUSH (bukan Pull Request)
    if: github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Siapkan Mesin Build Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build & Push Image API
      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Ganti format tag sesuai username dockerhub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-inventory-api:latest

      # 4. Build & Push Image Worker (Opsional, tapi bagus sekalian)
      - name: Build and push Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-inventory-worker:latest
